**Créez vos premiers arrays avec NumPy :**


In [15]:
import numpy as np

revenus = [1800, 1500, 2200, 3000, 2172]

np.mean(revenus)


2134.4

Un des avantages majeurs de Numpy est la notion d'Array qui vient avec. Ils sont semblables aux listes classiques de Python mais permettent des opérations bien plus rapides (jusqu'à 30 fois à mesure que la taille de l'Array augmente). 

Contrairement aux listes Python, on ne peut stocker qu'un seul type de variable dans un Array.

In [3]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


Pour créer un array NumPy, le plus simple est de commencer par une liste Python classique (telle que la liste "revenus" ci-dessus). 

Si la liste Python contient des variables de plusieurs types, NumPy s'efforcera de les convertir dans le type le plus général au moment de créer l'Array. 

Par exemple si une liste contient des int et des float, NumPy les convertira toutes en float.

In [4]:
revenus = [1800, 1500, 2200, 3000, 2172]

revenus_array = np.array(revenus) 

Numpy permet également de créer des arrays selon différents patterns :

In [ ]:
np.zeros(n) #permet de créer un array rempli de 0, de n éléments ;
np.ones(n) #similaire en tous points à la fonction présentée ci-dessus, à la différence que l’array sera rempli cette fois-ci de 1 ;
np.arange(i, j, p)  #permet de créer un array rempli avec une séquence linéaire, qui ira de  i  à  j, par pas de  p  ;
np.linspace(i, j, n) #permet de créer un array de  n  valeurs espacées uniformément entre  i  et  j.

In [8]:
revenus_array.dtype #permet de connaître le type (int, float, etc.) et la précision (8, 16, 32bits etc.) du type de variables dans l'array

dtype('int32')

La manipulation des array est similaire aux listes classiques :

**Sélectionner des éléments au sein d'un array**

In [ ]:
# pour accéder au 5ème élement
revenus_array[4] 
# pour accéder au dernier élément
revenus_array[-1]
# On peut aussi modifier les valeurs
revenus_array[1] = 1900

Accéder à plusieurs éléments contigus :

nom_array[i,j,p] avec i indice de départ, j indice 

In [9]:
# Les 3 premiers éléments
print(revenus_array[:3])
# Les éléments à partir de l’indice 2
print(revenus_array[2:])
# Un élément sur deux
print(revenus_array[::2])

# Si le pas est négatif, le début et la fin sont inversés:
print(revenus_array[::-1])

[1800 1500 2200]
[2200 3000 2172]
[1800 2200 2172]
[2172 3000 2200 1500 1800]


On peut également accéder à des éléments d'un array selon une condition :

In [10]:
print(revenus_array[revenus_array > 2000])

[2200 3000 2172]


In [ ]:
# On peut combiner les conditions : 
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

# A noter : dans ce cas le "et" logique s'écrit &, et le "ou" logique s'écrit |

# On peut donc modifier certaines valeurs sous condition : 
revenus_array[revenus_array > 2000] = 0

**Les méthodes d'array :**

In [13]:
# Comme vu précédemment, la méthode .dtype permet d'obtenir le type et la précision d'un array

# La méthode .shape permet d'obtenir ses dimensions
revenus_array.shape

# On peut également appliquer de nombreuses opérations mathématiques :

# calculer la moyenne
revenus_array.mean()
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()
# accéder à l’indice de l’élement minimum (ou maximum) :
revenus_array.argmin()
revenus_array.argmax()
# ordonner par ordre croissant :
revenus_array.sort()
print(revenus_array)
# calculer la somme :
revenus_array.sum()

[1500 1800 2172 2200 3000]


10672

**Exercice :**

https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C3%20-%20Cr%C3%A9ez%20vos%20premiers%20arrays%20avec%20Numpy.ipynb

**Correction :**
https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C3%20-%20Cr%C3%A9ez%20vos%20premiers%20arrays%20avec%20Numpy%20-%20correction.ipynb#scrollTo=16fe3f16

**TL;DR**

* NumPy (pour Numerical Python) est une librairie Python permettant de manipuler et d’effectuer rapidement et simplement de nombreuses opérations mathématiques sur un tableau de données.

* Les données sont stockées dans une structure similaire à une liste Python, un tableau NumPy, ou array.

* Ce dernier, contrairement à une liste, est obligatoirement monotype.

* On peut sélectionner au sein d’un array :

    * un élément via son indice avec l’écriture :  nom_array[indice]  ;

    * plusieurs éléments contigus via la syntaxe :  nom_array[début:fin:pas]  ;

    * certains éléments spécifiques via une condition :  nom_array[condition]  .

* Les arrays possèdent de nombreuses méthodes permettant de les manipuler ou d'effectuer des opérations mathématiques, de façon très simple.

## Arrays à deux dimensions

On peut créer des array qui contiennent plusieurs colonnes (array à deux dimensions)

Pour cela le plus simple est de partir d'une liste de listes :

In [14]:
# Ex : pour chaque client d'une banque, on a une liste des informations suivantes : revenu mensuel, mensualité et âge

hugo = [1200, 400, 22]
richard = [1700, 500, 33]
paul = [2400, 400, 28]
jacques = [2500, 600, 38]
emile = [3000, 800, 25]

# On crée une liste de listes :

tableau = [hugo, richard, paul, jacques, emile]
tableau

[[1200, 400, 22],
 [1700, 500, 33],
 [2400, 400, 28],
 [2500, 600, 38],
 [3000, 800, 25]]

In [16]:
# Puis on convertit cette liste de liste en array NumPy :
data = np.array(tableau)
data

array([[1200,  400,   22],
       [1700,  500,   33],
       [2400,  400,   28],
       [2500,  600,   38],
       [3000,  800,   25]])

Ces arrays sont comparables à des matrices mathématiques. 
On peut faire la somme de deux matrices de mêmes dimensions via la formule A+B (avec A et B les matrices)
On peut faire le produit matriciel de deux matrices avec A @ B
On peut calculer le produit terme à terme avec A * B

In [18]:
# On peut sélectionner la cellule d'un array via la formule 
data[0,0] # pour sélectionne la ligne 1, colonne 1

# On peut séledctionner toute une ligne ou colonne avec " : "
data[:,2] # sélectionnera toutes les cases de la troisieme colonne

array([22, 33, 28, 38, 25])

In [19]:
# On peut également faire des sélections par condition :
data[data[:,2] < 30]

array([[1200,  400,   22],
       [2400,  400,   28],
       [3000,  800,   25]])

In [21]:
data[:,2][data[:,2] < 30]

[ True False  True False  True]


In [22]:
# Pour ajouter une ligne à un array, on peut utiliser la méthode vstack :

fred = [1200, 200, 20]
np.vstack((data, fred))

array([[1200,  400,   22],
       [1700,  500,   33],
       [2400,  400,   28],
       [2500,  600,   38],
       [3000,  800,   25],
       [1200,  200,   20]])

**Exercice "Transformez vos données en tableau"**

https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C4%20-%20Transformez%20vos%20donn%C3%A9es%20en%20tableaux.ipynb

**Correction**

https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C4%20-%20Transformez%20vos%20donn%C3%A9es%20en%20tableaux%20-%20correction.ipynb

In [29]:
a = np.linspace(5, 10, 11)
print(a[-3:-1])

a[a % 2 == 0]

[9.  9.5]


array([ 6.,  8., 10.])

In [30]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])
b.shape

(3, 2, 2)